fix: add missing closing bracket when flexsearch index is empty
In a new site that does not have any pages yet, it was causing an error

```
❯ hugo server -v
Start building sites …
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown
INFO 2023/05/13 17:42:47 syncing static files to /
INFO 2023/05/13 17:42:47 postcss: use config file <path_to_project>/themes/gruvbox/postcss.config.js
INFO 2023/05/13 17:42:47 postcss: use config file <path_to_project>/themes/gruvbox/postcss.config.js
Error: Error building site: JSBUILD: failed to transform "js/flexsearch.js" (text/javascript): "<path_to_project>/themes/gruvbox/assets/js/flexsearch.js:75:2": Unexpected ";"
Built in 603 ms
```